# Generated by Django 6.0.3 on 2026-03-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рисунок', 'verbose_name_plural': 'Рисунки'},
        ),
    ]
