# Generated by Django 6.0.3 on 2026-03-31 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_drawing_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкое'), ('medium', 'Среднее'), ('hard', 'Сложное')], default='medium', max_length=10)),
                ('used_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['word'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='current_drawer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='max_turns',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='room',
            name='round_time_left',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='room',
            name='score_creator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='score_participant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='turn_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='mode',
            field=models.CharField(choices=[('free', 'Свободное рисование'), ('turn', 'По очереди'), ('mirror', 'Зеркало'), ('guess', 'Угадай рисунок')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='GuessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_attempts', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.word')),
            ],
            options={
                'verbose_name': 'Попытка угадывания',
                'verbose_name_plural': 'Попытки угадывания',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='current_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.word'),
        ),
    ]
