# Generated by Django 6.0.3 on 2026-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_word_room_current_drawer_room_max_turns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_word',
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_drawer',
        ),
        migrations.RemoveField(
            model_name='room',
            name='round_time_left',
        ),
        migrations.RemoveField(
            model_name='room',
            name='score_creator',
        ),
        migrations.RemoveField(
            model_name='room',
            name='score_participant',
        ),
        migrations.AlterField(
            model_name='room',
            name='mode',
            field=models.CharField(choices=[('free', 'Свободное рисование'), ('turn', 'По очереди'), ('mirror', 'Зеркало')], default='free', max_length=20),
        ),
        migrations.DeleteModel(
            name='GuessAttempt',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
