# Generated by Django 6.0.3 on 2026-04-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_current_word_remove_room_current_drawer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='image_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
