# Generated by Django 6.0.3 on 2026-03-31 12:16

from django.db import migrations, models


def fix_duplicate_emails(apps, schema_editor):
    """Обрабатывает дубликаты email, добавляя username к email"""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    
    # Находим дубликаты email
    duplicates = CustomUser.objects.values('email').annotate(
        count=models.Count('email')
    ).filter(count__gt=1)
    
    for dup in duplicates:
        users = CustomUser.objects.filter(email=dup['email'])
        # Первому пользователю оставляем email, остальным добавляем username
        for i, user in enumerate(users):
            if i > 0:
                user.email = f"{user.username}_{user.id}@local.dev"
                user.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_emails, migrations.RunPython.noop),
    ]
